### ISSUE TITLE
rejoin former master fails

### ISSUE THREAD

**Issue by jankeirse** [zalando/patroni#167]
I'm not entirely sure if this is expected behaviour or not. If I stop a master (systemctl stop patroni) a slave takes over. This works fine. If I then want to rejoin the master as slave using just systemctl start patroni it fails: 

> < 2016-03-31 09:13:38.119 CEST >ERROR:  requested starting point 0/26000000 on timeline 5 is not in this server's history
> < 2016-03-31 09:13:38.119 CEST >DETAIL:  This server's history forked from timeline 5 at 0/250001A8.

I can fix it by manually running pg_rewind on the former master:
` sudo -u postgres pg_rewind -D /var/lib/pgsql/9.5/data --source-server='host=currentmaster password=pwforpostgres' 
`
After running that command the former master can join again as slave and everything appears to work. Looking at the code I see that there is quite a bit of code there for running pg_rewind already so I am wondering if I have hit a bug or if this is how it is expected to work and I should always manually intervene before rejoining a former master even if it was shut down manually (not crashed.)

**Comment by alexeyklyukin** [comment]
You have to configure the username and the password for pg_rewind first (i.e. https://github.com/zalando/patroni/blob/master/postgres0.yml). Create a pg_rewind section in the patroni configuration file and specify there the superuser username and the password, i.e.
pg_rewind:
    username: postgres
    password: pwforpostgres

I assume you have set either the wal_log_hints or enabled the checksum, because this is a prerequisite to running pg_rewind.

**Comment by CyberDem0n** [comment]
Hmm, usually pg_rewind is not necessary if patroni (postgres) was shut down cleanly.
How it works:

1. `systemctl stop patroni` sends (hopefully) `SIGTERM` to patroni
2. patroni handles this signal and shuts down postgres with: `pg_ctl stop -m fast`
3. after clean shutdown of postgres patroni removes `leader` lock from etcd (or zookeeper)
4. one of replicas acquires leader lock and promote.

What can go wrong?
It could happen that patroni was not able to shut down postgres during 10 seconds (https://github.com/zalando/patroni/blob/master/extras/startup-scripts/patroni.service#L21) and was killed with `SIGKILL`. In this case replica has a chance to promote earlier then former master was shut down.

In order to get full picture and answer all questions I need to get:

1. config yaml file from the former master
2. patroni logs from the former master (starting from the moment when you run  `systemctl stop patroni`)
3. postgres logs from the former master (starting from the moment when you run  `systemctl stop patroni`)

And also please check, that after execution of `systemctl stop patroni` there is no postgres running on this host any more.

**Comment by jankeirse** [comment]
@alexeyklyukin Yes wal_log_hints is on and I have tried with both data-checksums of and on. The pg_rewind settings are also there (assuming that is supposed to be the postgres  pasword for the database, not for the OS user.)

**Comment by jankeirse** [comment]
@CyberDem0n Sorry for the delay, found the time to get all the requested info:
[logfiles.txt](https://github.com/zalando/patroni/files/204181/logfiles.txt)

[patroni.yaml.txt](https://github.com/zalando/patroni/files/204183/patroni.yaml.txt)

**Comment by jankeirse** [comment]
ps.: I can reproduce this every time (you can actually see from the logfile the slave is just starting for the first time and creating the new replication slot.)

**Comment by CyberDem0n** [comment]
**< 2016-04-05 11:11:11.130 CEST >LOG:  received smart shutdown request**
< 2016-04-05 11:11:11.130 CEST >LOG:  autovacuum launcher shutting down
< 2016-04-05 11:11:11.130 CEST >FATAL:  terminating connection due to administrator command
< 2016-04-05 11:11:11.130 CEST >FATAL:  terminating connection due to administrator command
< 2016-04-05 11:11:11.137 CEST >LOG:  shutting down
< 2016-04-05 11:11:11.147 CEST >FATAL:  the database system is shutting down
**< 2016-04-05 11:11:11.232 CEST >LOG:  received fast shutdown request**

Somehow postgres received two shutdown requests. But only one of then actually was initiated by patroni, the last one (fast shutdown).
Replica stopped streaming right after the first shutdown request (smart) and didn't got latest changes. Actually it should be solved by pg_rewind, but somehow it was not called...

Now we need to figure out who and why sends smart shutdown request. I guess it was sent by `systemctl`

```
KillMode=

    Specifies how processes of this unit shall be killed. One of control-group, process, mixed, none.

    If set to control-group, all remaining processes in the control group of this unit will be killed on unit stop (for services: after the stop command is executed, as configured with ExecStop=). If set to process, only the main process itself is killed. If set to mixed, the SIGTERM signal (see below) is sent to the main process while the subsequent SIGKILL signal (see below) is sent to all remaining processes of the unit's control group. If set to none, no process is killed. In this case, only the stop command will be executed on unit stop, but no process be killed otherwise. Processes remaining alive after stop are left in their control group and the control group continues to exist after stop unless it is empty.

    Processes will first be terminated via SIGTERM (unless the signal to send is changed via KillSignal=). Optionally, this is immediately followed by a SIGHUP (if enabled with SendSIGHUP=). If then, after a delay (configured via the TimeoutStopSec= option), processes still remain, the termination request is repeated with the SIGKILL signal (unless this is disabled via the SendSIGKILL= option). See kill(2) for more information.

    Defaults to control-group.
```

At least in our example we didn't changed KillMode, so probably it defaults to `control-group`.
If you are using not the latest version of patroni (which doesn't include https://github.com/zalando/patroni/commit/7b524bc5571f2c49d7375d2cbd4eb3c7d303dca8), then it could explain such behaviour.

In any case please try to update your service file and set `KillMode=process`, hopefully it should help.

**Comment by jankeirse** [comment]
Thanks, this does indeed solve the problem!

**Comment by CyberDem0n** [comment]
For me it is still not clear why patroni was not calling pg_rewind...

**Comment by jankeirse** [comment]
True, it is still reproducible by sending the kill signals systemd is sending manually. 
So first ps -ef | grep postgres (assuming patroni and postgres run as postgres user) and then a single kill command with a list of all the pid's.

**Comment by franciscoreinolds** [comment]
Hey all,

I just wanted to mention that we just experienced this, despite the `KillMode=process`, so there might be more to this issue.

Exactly the same as documented in this [comment](https://github.com/patroni/patroni/issues/167#issuecomment-205765549), Postgres received two shutdown requests.

We also just tried replacing `patroni`'s `KillMode` to `mixed`, and that changed nothing, the unclean shutdown and data loss from timeline forking are still present. 

 > For me it is still not clear why patroni was not calling pg_rewind...

This is also the case for us.
