### ISSUE TITLE
Fail to start Patroni with an existing data directory

### ISSUE THREAD

**Issue by EtienneM** [zalando/patroni#913]
Hi,

I am struggling with the following use case. I have a PostgreSQL 10.4 without Patroni running and I
want to upgrade it PostgreSQL 10.6 with Patroni. I tried to follow this comment
https://github.com/zalando/patroni/issues/526#issuecomment-331150033 recommendation but it does not
work. Here is what I do:

1. Stop PostgreSQL 10.4
2. Start PostgreSQL 10.6 and wait for it to be ready
3. Create Patroni super-user
4. Start Patroni
5. `patronictl -k restart --force CLUSTER NODE`

After step 4, if I try to connect to my database I have this message:

```
psql: FATAL:  no pg_hba.conf entry for host "10.255.0.2", user "biniou_2616", database "biniou_2616", SSL off
```

It seems it uses the pg_hba configuration from the previous PostgreSQL without Patroni and not the
one from Patroni... Note that in this case, I have this in the Patroni logs in a loop:

```
2019-01-08 15:01:37.633270797 +0100 CET [postgresql-2] 2019-01-08 14:01:37,632 INFO: Failed to import patroni.dcs.consul
2019-01-08 15:01:37.651205713 +0100 CET [postgresql-2] 2019-01-08 14:01:37,650 INFO: Selected new etcd server http://172.17.0.1:2381
2019-01-08 15:01:37.664788901 +0100 CET [postgresql-2] 2019-01-08 14:01:37,663 INFO: establishing a new patroni connection to the postgres cluster
2019-01-08 15:01:37.699635809 +0100 CET [postgresql-2] 2019-01-08 14:01:37,699 WARNING: Could not activate Linux watchdog device: "Can't open watchdog device: [Errno 2] No such file or directory: '/dev/watchdog'"
2019-01-08 15:01:37.703192316 +0100 CET [postgresql-2] 2019-01-08 14:01:37,702 INFO: acquired session lock as a leader
2019-01-08 15:01:47.695820420 +0100 CET [postgresql-2] 2019-01-08 14:01:47,695 INFO: no action.  i am the leader with the lock
2019-01-08 15:01:47.687896263 +0100 CET [postgresql-2] 2019-01-08 14:01:47,687 INFO: Lock owner: biniou-6999; I am biniou-6999
2019-01-08 15:01:47.682375335 +0100 CET [postgresql-2] 2019-01-08 14:01:47,681 INFO: Lock owner: biniou-6999; I am biniou-6999
2019-01-08 15:01:52.323789185 +0100 CET [postgresql-2] 2019-01-08 14:01:52 UTC LOG:  08P01: incomplete startup packet
2019-01-08 15:01:52.323799678 +0100 CET [postgresql-2] 2019-01-08 14:01:52 UTC LOCATION:  ProcessStartupPacket, postmaster.c:1964
2019-01-08 15:01:57.694384155 +0100 CET [postgresql-2] 2019-01-08 14:01:57,693 INFO: no action.  i am the leader with the lock
2019-01-08 15:01:57.686729002 +0100 CET [postgresql-2] 2019-01-08 14:01:57,685 INFO: Lock owner: biniou-6999; I am biniou-6999
2019-01-08 15:02:02.690468344 +0100 CET [postgresql-2] 2019-01-08 14:02:02 UTC LOG:  08P01: incomplete startup packet
```

The `incomplete startup packet` seems weird to me but I have no idea where does it come from.

Then, if I do the step 5 I have this message

```
Failed: restart for member biniou-6999, status code=503, (restart failed)
```

And these messages in the logs:

```
2019-01-08 15:06:47.684624575 +0100 CET [postgresql-2] 2019-01-08 14:06:47,683 INFO: Lock owner: biniou-6999; I am biniou-6999
2019-01-08 15:06:47.765280260 +0100 CET [postgresql-2] 2019-01-08 14:06:47 UTC FATAL:  57P01: terminating connection due to administrator command
2019-01-08 15:06:47.781654986 +0100 CET [postgresql-2] 2019-01-08 14:06:47 UTC LOG:  00000: shutting down
2019-01-08 15:06:47.688599718 +0100 CET [postgresql-2] 2019-01-08 14:06:47,688 INFO: updated leader lock during restart
2019-01-08 15:06:47.778591826 +0100 CET [postgresql-2] 2019-01-08 14:06:47 UTC LOCATION:  LogChildExit, postmaster.c:3605
2019-01-08 15:06:47.765293360 +0100 CET [postgresql-2] 2019-01-08 14:06:47 UTC LOCATION:  ProcessInterrupts, postgres.c:2913
2019-01-08 15:06:47.781699911 +0100 CET [postgresql-2] 2019-01-08 14:06:47 UTC LOCATION:  ShutdownXLOG, xlog.c:8421
2019-01-08 15:06:47.778225101 +0100 CET [postgresql-2] 2019-01-08 14:06:47 UTC LOG:  00000: worker process: logical replication launcher (PID 71) exited with exit code 1
2019-01-08 15:06:47.757687257 +0100 CET [postgresql-2] 2019-01-08 14:06:47 UTC LOG:  00000: aborting any active transactions
2019-01-08 15:06:47.757286537 +0100 CET [postgresql-2] 2019-01-08 14:06:47 UTC LOCATION:  pmdie, postmaster.c:2723
2019-01-08 15:06:47.757269676 +0100 CET [postgresql-2] 2019-01-08 14:06:47 UTC LOG:  00000: received fast shutdown request
2019-01-08 15:06:47.757766426 +0100 CET [postgresql-2] 2019-01-08 14:06:47 UTC LOCATION:  pmdie, postmaster.c:2756
2019-01-08 15:06:47.831651650 +0100 CET [postgresql-2] 2019-01-08 14:06:47,828 INFO: closed patroni connection to the postgresql cluster
2019-01-08 15:06:47.821871738 +0100 CET [postgresql-2] 2019-01-08 14:06:47 UTC LOCATION:  UnlinkLockFiles, miscinit.c:765
2019-01-08 15:06:47.821840827 +0100 CET [postgresql-2] 2019-01-08 14:06:47 UTC LOG:  00000: database system is shut down
2019-01-08 15:06:48.342183275 +0100 CET [postgresql-2] localhost:5432 - no response
2019-01-08 15:06:48.337245700 +0100 CET [postgresql-2] 2019-01-08 14:06:48,336 INFO: postmaster pid=360
2019-01-08 15:06:49.346153292 +0100 CET [postgresql-2] 2019-01-08 14:06:49,344 ERROR: postmaster is not running
2019-01-08 15:06:49.423152561 +0100 CET [postgresql-2] 2019-01-08 14:06:49,421 INFO: removed leader key after trying and failing to start postgres
2019-01-08 15:06:49.380036322 +0100 CET [postgresql-2] 2019-01-08 14:06:49,377 INFO: Lock owner: biniou-6999; I am biniou-6999
2019-01-08 15:06:59.377996649 +0100 CET [postgresql-2] 2019-01-08 14:06:59,375 WARNING: Postgresql is not running.
2019-01-08 15:06:59.409584079 +0100 CET [postgresql-2] 2019-01-08 14:06:59,407 INFO: Lock owner: None; I am biniou-6999
2019-01-08 15:06:59.380574574 +0100 CET [postgresql-2] 2019-01-08 14:06:59,376 INFO: Lock owner: None; I am biniou-6999
2019-01-08 15:06:59.457321211 +0100 CET [postgresql-2] 2019-01-08 14:06:59,456 INFO: starting as a secondary
2019-01-08 15:06:59.454278316 +0100 CET [postgresql-2] 2019-01-08 14:06:59,451 INFO: Lock owner: None; I am biniou-6999
2019-01-08 15:06:59.858618661 +0100 CET [postgresql-2] 2019-01-08 14:06:59,858 INFO: postmaster pid=371
2019-01-08 15:06:59.867158399 +0100 CET [postgresql-2] localhost:5432 - no response
2019-01-08 15:07:00.895333744 +0100 CET [postgresql-2] 2019-01-08 14:07:00,893 INFO: Lock owner: None; I am biniou-6999
2019-01-08 15:07:00.905223168 +0100 CET [postgresql-2] 2019-01-08 14:07:00,903 INFO: failed to start postgres
2019-01-08 15:07:00.871008431 +0100 CET [postgresql-2] 2019-01-08 14:07:00,869 ERROR: postmaster is not running
```

Which tells me PostgreSQL is not running without further explanation. Do you know how I can get
the reason why PostgreSQL is not running? I have nothing else in the logs.

Thanks a lot for your help

**Comment by CyberDem0n** [comment]
Hi,

Unfortunately the real error reported by postgres and explaining why it fails to start is not visible due to a wrong redirection of stderr to stdout. It is already fixed in the master via https://github.com/zalando/patroni/pull/896.
Could you please apply the patch and try again?
Also it would be good if you share your patroni config file.

**Comment by EtienneM** [comment]
Oh yes! Thanks a lot!!! It's easier with PostgreSQL logs :sweat_smile:

The PostgreSQL error message is clear now:

```
[postgresql-2] 2019-01-08 17:01:15 UTC LOG:  58P01: could not open configuration file "/etc/postgresql/10/main/pg_hba.conf": No such file or directory
```

But isn't Patroni supposed to generate it based on the patroni.yml file? Anyway, I just kept the
configuration from the PostgreSQL version without Patroni and it works. I still have this message
in the logs which I don't have when directly starting Patroni cluster (without keeping a data
directory):

```
 [postgresql-2] 2019-01-09 11:10:46 UTC LOG:  08P01: incomplete startup packet
[postgresql-2] 2019-01-09 11:10:46 UTC LOCATION:  ProcessStartupPacket, postmaster.c:1964
```

I can't find the root cause of this. Any idea? The cluster is reachable so it might not be critical
but it's a bit disturbing...

**Comment by CyberDem0n** [comment]
> isn't Patroni supposed to generate it based on the patroni.yml file

Well, it depends on where `pg_hba` is configured.
If it is in the `bootstrap` section (an I assume that was your case), it will be applied only when Patroni bootstraps a new cluster (initdb or custom bootstrap). In your case the PGDATA was not empty, therefore no bootstrap happened.

> Do you want me to write something in Patroni documentation about the procedure of updating from a PostgreSQL without Patroni to PostgreSQL with Patroni and keeping the data directory?

It would be great.
